using NpgsqlTypes;

namespace CvManager.Models;

// A candidate's project. Positions pick projects by tag, so the tags are the
// part that matters for CV generation.
public class Project : IVersioned
{
    public int Id { get; set; }

    public string UserId { get; set; } = "";
    public ApplicationUser? User { get; set; }

    public string Name { get; set; } = "";

    public DateOnly StartDate { get; set; }

    // Null means the project is still running ("present" in the UI).
    public DateOnly? EndDate { get; set; }

    // Markdown source. Rendered with Markdig when displayed, never stored as HTML.
    public string? DescriptionMarkdown { get; set; }

    public int Version { get; set; }

    // Generated by Postgres from Name + DescriptionMarkdown, GIN indexed.
    public NpgsqlTsVector? SearchVector { get; set; }

    public List<ProjectTag> ProjectTags { get; set; } = [];
}

// Technology tags. Shared across all users and created on first use, which is
// how tag inputs normally behave - the autocomplete just queries this table.
public class Tag
{
    public int Id { get; set; }

    // Stored lowercase and trimmed so "Python", "python" and " Python " are one
    // tag. The unique index is on this column.
    public string Name { get; set; } = "";

    public List<ProjectTag> ProjectTags { get; set; } = [];

    public List<PositionProjectTag> PositionProjectTags { get; set; } = [];
}

// Join table for the many-to-many between projects and tags. I declare it
// explicitly instead of letting EF create a hidden one, because the tag cloud
// and the project filter both query it directly.
public class ProjectTag
{
    public int ProjectId { get; set; }
    public Project? Project { get; set; }

    public int TagId { get; set; }
    public Tag? Tag { get; set; }
}
