using CvManager.Models;
using CvManager.Models.ViewModels;
using QRCoder;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CvManager.Services;

// Optional extra: a printable CV with a QR code that links back to the live
// page. QuestPDF builds the document, QRCoder draws the code - neither is
// hand-rolled.
public class CvPdfService
{
    private readonly MarkdownRenderer _markdown;

    public CvPdfService(MarkdownRenderer markdown)
    {
        _markdown = markdown;
    }

    public byte[] Render(CvViewModel cv, string cvUrl)
    {
        var qr = BuildQrCode(cvUrl);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                // Lato is the font QuestPDF bundles. Naming a system font such as
                // Calibri would work on Windows and then fail in the Linux
                // container, which has no such font installed.
                page.DefaultTextStyle(style => style.FontSize(10).FontFamily("Lato"));

                page.Header().Element(header => ComposeHeader(header, cv, qr));
                page.Content().Element(content => ComposeContent(content, cv));

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by CV Manager · ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span(cvUrl).FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void ComposeHeader(IContainer container, CvViewModel cv, byte[] qr)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text(cv.FullName).FontSize(20).SemiBold();
                column.Item().Text(cv.Position.Title).FontSize(12).FontColor(Colors.Blue.Darken2);

                var subtitle = string.Join(" · ", new[]
                {
                    cv.Position.Company,
                    cv.Location,
                    cv.Candidate.Email
                }.Where(s => !string.IsNullOrWhiteSpace(s)));

                column.Item().Text(subtitle).FontSize(9).FontColor(Colors.Grey.Darken1);
            });

            // The QR code points at this CV's page, so a printed copy leads back
            // to the live version.
            row.ConstantItem(70).Image(qr);
        });
    }

    private static void ComposeContent(IContainer container, CvViewModel cv)
    {
        container.PaddingVertical(15).Column(column =>
        {
            column.Spacing(12);

            column.Item().Text("Details").FontSize(12).SemiBold().FontColor(Colors.Grey.Darken2);

            foreach (var row in cv.Attributes)
            {
                column.Item().Row(line =>
                {
                    line.ConstantItem(140).Text(row.Attribute.Name).SemiBold();

                    // Missing values are called out in the print-out the same way
                    // they are on screen.
                    if (row.HasValue)
                    {
                        line.RelativeItem().Text(DisplayFor(row));
                    }
                    else
                    {
                        line.RelativeItem().Text("not filled in").FontColor(Colors.Red.Medium).Italic();
                    }
                });
            }

            if (cv.Projects.Count > 0)
            {
                column.Item().PaddingTop(8).Text("Projects").FontSize(12).SemiBold()
                    .FontColor(Colors.Grey.Darken2);

                foreach (var project in cv.Projects)
                {
                    column.Item().Column(block =>
                    {
                        block.Item().Text(project.Name).SemiBold();

                        var period = $"{project.StartDate:MMM yyyy} - " +
                                     (project.EndDate?.ToString("MMM yyyy") ?? "present");
                        block.Item().Text(period).FontSize(9).FontColor(Colors.Grey.Darken1);

                        if (!string.IsNullOrWhiteSpace(project.DescriptionMarkdown))
                        {
                            // The PDF shows the markdown source as plain text -
                            // rendering HTML into a PDF would need a converter and
                            // the descriptions are short.
                            block.Item().Text(project.DescriptionMarkdown).FontSize(9);
                        }

                        var tags = string.Join(", ", project.ProjectTags.Select(t => t.Tag?.Name));
                        if (tags.Length > 0)
                        {
                            block.Item().Text(tags).FontSize(8).FontColor(Colors.Blue.Darken1);
                        }
                    });
                }
            }
        });
    }

    private static string DisplayFor(CvAttributeRow row)
    {
        // Image attributes hold a URL; printing the address is more useful than
        // printing nothing.
        return row.Attribute.Type == AttributeType.Image
            ? row.Value?.ValueString ?? string.Empty
            : row.DisplayText;
    }

    private static byte[] BuildQrCode(string url)
    {
        using var generator = new QRCodeGenerator();
        using var data = generator.CreateQrCode(url, QRCodeGenerator.ECCLevel.Q);
        using var png = new PngByteQRCode(data);
        return png.GetGraphic(8);
    }
}
